-- Bootstrap the template's sample CRUD tables plus a durable workflow state store.

BEGIN;

CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT appointments_time_range CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_appointments_start_time_end_time
    ON appointments (start_time, end_time);

CREATE TABLE IF NOT EXISTS workflow_state_store (
    workflow_id TEXT PRIMARY KEY,
    workflow_type TEXT NOT NULL,
    current_state TEXT NOT NULL,
    status TEXT NOT NULL,
    state_version INTEGER NOT NULL DEFAULT 1,
    input_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    state_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_transition_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT workflow_state_store_state_version CHECK (state_version > 0)
);

CREATE INDEX IF NOT EXISTS idx_workflow_state_store_type_status_updated_at
    ON workflow_state_store (workflow_type, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_workflow_state_store_current_state_updated_at
    ON workflow_state_store (current_state, updated_at DESC);

CREATE TABLE IF NOT EXISTS workflow_state_transitions (
    transition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id TEXT NOT NULL REFERENCES workflow_state_store (workflow_id) ON DELETE CASCADE,
    previous_state TEXT,
    next_state TEXT NOT NULL,
    transition_name TEXT NOT NULL,
    transition_status TEXT NOT NULL DEFAULT 'applied',
    transition_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_workflow_state_transitions_workflow_created_at
    ON workflow_state_transitions (workflow_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_workflow_state_transitions_status_created_at
    ON workflow_state_transitions (transition_status, created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_documents_updated_at ON documents;
CREATE TRIGGER set_documents_updated_at
BEFORE UPDATE ON documents
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS set_appointments_updated_at ON appointments;
CREATE TRIGGER set_appointments_updated_at
BEFORE UPDATE ON appointments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS set_workflow_state_store_updated_at ON workflow_state_store;
CREATE TRIGGER set_workflow_state_store_updated_at
BEFORE UPDATE ON workflow_state_store
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS set_workflow_state_transitions_updated_at ON workflow_state_transitions;
CREATE TRIGGER set_workflow_state_transitions_updated_at
BEFORE UPDATE ON workflow_state_transitions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

COMMIT;
